name: Publish
on:
  push:
    tags:
      - '*.*.*.*'
jobs:
  Build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get Environment Variables
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Download Dalamud Latest
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          if ($?) {
            Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
          } else {
            Write-Error "Failed to download Dalamud Latest"
            exit 1
          }

      - name: Restore Nuget Packages
        run: dotnet restore ArgentiRotations/ArgentiRotations.csproj
      - name: Build Rotations
        run: dotnet build --no-restore -c Release ArgentiRotations/ArgentiRotations.csproj -p:AssemblyVersion=$env:tag -p:FileVersion=$env:tag -p:InformationalVersion=$env:tag --output .\build

      - name: Publish Rotations
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/ArgentiRotations.dll
            ./build/ArgentiRotations.pdb
          token: ${{ secrets.GITHUB_TOKEN }}